Repository NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819, pull requests merged in 2019-05, with the labels that each got.

#70 Finally added a footer
  UI-MVC/Controllers/HomeController.cs
  UI-MVC/Views/Home/About.cshtml
  UI-MVC/Views/Home/Privacy.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#71 Feature/admin/new ideation
  BL/ModuleManager.cs
  DAL/ExtensionMethods.cs
  DAL/repos/IdeationRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Projects/Module.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Models/CreateIdeationModel.cs
  UI-MVC/Models/CreateIdeationQuestionModel.cs
  UI-MVC/Models/CreateTagModel.cs
  UI-MVC/Services/UserService.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Moderation/AddTag.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
Labels: Master Worthy

#76 Ideation Thread is finished
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Models/LikeViewModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
Labels: Master Worthy

#78 Feature/logged in/vote idea
  BL/IdeationQuestionManager.cs
  BL/VoteManager.cs
  DAL/Data Transfer Objects/VotesDTO.cs
  DAL/repos/IdeationVoteRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  Domain/UserInput/Vote.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
Labels: Master Worthy

#81 Pimp My Website & Some Ideation Progress
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  BL/PlatformManager.cs
  BL/VoteManager.cs
  DAL/Data Transfer Objects/VotesDTO.cs
  DAL/ExtensionMethods.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Projects/Module.cs
  Domain/UserInput/Vote.cs
  UI-MVC/Controllers/HomeController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Models/CreateIdeationModel.cs
  UI-MVC/Models/CreateIdeationQuestionModel.cs
  UI-MVC/Models/CreateTagModel.cs
  UI-MVC/Models/LikeViewModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Home/About.cshtml
  UI-MVC/Views/Home/HomeTemplates/PlatformCarousel.cshtml
  UI-MVC/Views/Home/HomeTemplates/PlatformList.cshtml
  UI-MVC/Views/Home/Index.cshtml
  UI-MVC/Views/Home/Privacy.cshtml
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Moderation/AddTag.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/Search.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/images/antwerpen.jpg
Labels: Master Worthy

#79 Fixed OAuth and logins
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml.cs
  UI-MVC/Startup.cs
  UI-MVC/appsettings.json
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/images/Microsoft.svg
Labels: Master Worthy

#83 Add new questionnaire
  BL/ProjectManager.cs
  DAL/DAL.csproj
  DAL/repos/IdeationRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  IP-TSI-CityOfIdeas.sln
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Models/CreateQuestionnaireModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/UIMVC.csproj
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml.cs
  UI-MVC/Views/Admin/AddQuestionnaireQuestion.cshtml
  UI-MVC/Views/Admin/AddQuestionnaireQuestion.cshtml.cs
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml.cs
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/EditPlatform.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/package-lock.json
Labels: Not Ready For Master

#87 Feature/admin/remove ideation
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/UserInput/Idea.cs
  UI-MVC/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/package-lock.json
  UI-MVC/webpack.config.js
  UI-MVC/wwwroot/dist/confirmemail.entry.js
  UI-MVC/wwwroot/dist/confirmemail.entry.js.map
  UI-MVC/wwwroot/dist/showmenu.entry.js
  UI-MVC/wwwroot/dist/showmenu.entry.js.map
  UI-MVC/wwwroot/js/collectallideas.js
Labels: Master Worthy

#86 CSS Part 1
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Ideation.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Phase.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Project.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Questionnaire.cshtml
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/Views/Shared/_TagsPartial.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#88 PRE SPRINT 2 PR
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  BL/ProjectManager.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/DAL.csproj
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/UserInput/Idea.cs
  IP-TSI-CityOfIdeas.sln
  UI-MVC/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml.cs
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Models/CreateQuestionnaireModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/Startup.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/UIMVC.csproj
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml.cs
  UI-MVC/Views/Admin/AddQuestionnaireQuestion.cshtml
  UI-MVC/Views/Admin/AddQuestionnaireQuestion.cshtml.cs
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml.cs
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Ideation.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Phase.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Project.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Questionnaire.cshtml
  UI-MVC/Views/Platform/EditPlatform.cshtml
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/Views/Shared/_TagsPartial.cshtml
  UI-MVC/appsettings.json
  UI-MVC/package-lock.json
  UI-MVC/webpack.config.js
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/confirmemail.entry.js
  UI-MVC/wwwroot/dist/confirmemail.entry.js.map
  UI-MVC/wwwroot/dist/showmenu.entry.js
  UI-MVC/wwwroot/dist/showmenu.entry.js.map
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/images/Microsoft.svg
  UI-MVC/wwwroot/js/collectallideas.js
Labels: Master Worthy

#89 Quick patch
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
Labels: Not Ready For Master

#90 Moderator verify users
  BL/UserManager.cs
  DAL/DAL.csproj
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Notas.txt
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Home/Index.cshtml
  UI-MVC/Views/Moderation/CollectAllUsers.cshtml
  UI-MVC/package-lock.json
  UI-MVC/package.json
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#92 Edit questionnaire
  BL/ProjectManager.cs
  BL/QuestionnaireQuestionManager.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Models/EditQuestionnaireModel.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml.cs
  UI-MVC/package-lock.json
Labels: Not Ready For Master

#93 Edit questionnaire (#92)
  BL/ProjectManager.cs
  BL/QuestionnaireQuestionManager.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Models/EditQuestionnaireModel.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml.cs
  UI-MVC/package-lock.json
Labels: Learning Git

#94 Feature/admin/alter ideation
  BL/ModuleManager.cs
  BL/ProjectManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Models/AlterIdeationModel.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Moderation/ChangeIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Shared/_TagsPartial.cshtml
  UI-MVC/package-lock.json
Labels: Master Worthy

#96 Feature/logged in/give idea
  BL/IdeationQuestionManager.cs
  BL/VoteManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
Labels: Master Worthy

#97 I flexed on Sprint 1: 300%
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  BL/ProjectManager.cs
  BL/QuestionnaireQuestionManager.cs
  BL/UserManager.cs
  BL/VoteManager.cs
  DAL/DAL.csproj
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/Models/AlterIdeationModel.cs
  UI-MVC/Models/EditQuestionnaireModel.cs
  UI-MVC/Notas.txt
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Admin/AddQuestionnaire.cshtml
  UI-MVC/Views/Admin/EditQuestionnaire.cshtml
  UI-MVC/Views/Home/Index.cshtml
  UI-MVC/Views/Moderation/AddIdeation.cshtml
  UI-MVC/Views/Moderation/ChangeIdeation.cshtml
  UI-MVC/Views/Moderation/CollectAllUsers.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml.cs
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/Views/Shared/_TagsPartial.cshtml
  UI-MVC/package-lock.json
  UI-MVC/package.json
Labels: Master Worthy

#101 Feature/logged in/add reaction
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/Index.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_LayoutRegular.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/Models/AddIdeaModel.cs
  UI-MVC/Models/IdeaViewModel.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Platform/Thread/_AddIdea.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
  UI-MVC/Views/Shared/_LoginPartial.cshtml
Labels: Master Worthy

#103 Feature/logged in/add reaction 2: Electric Boogaloo
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/Index.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_LayoutRegular.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/Models/AddIdeaModel.cs
  UI-MVC/Models/IdeaViewModel.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Platform/CollectIdeationThread.cshtml
  UI-MVC/Views/Platform/Thread/_AddIdea.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
  UI-MVC/Views/Shared/_LoginPartial.cshtml
Labels: Master Worthy

#109 Roles/implementation
  UI-MVC/Areas/Identity/IdentityHostingStartup.cs
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml.cs
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/Models/AssignRoleModel.cs
  UI-MVC/Services/RoleService.cs
  UI-MVC/Services/UserService.cs
  UI-MVC/Startup.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllUsers.cshtml
  UI-MVC/Views/Moderation/ModerationTemplates/AssignRolePartial.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/appsettings.json
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Denied Pull, Dev branch

#107 Feature/logged in/flag idea
  BL/IdeationQuestionManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Dev branch, Master Worthy

#108 Shomenu swooped
  BL/IdeationQuestionManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Areas/Identity/IdentityHostingStartup.cs
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml.cs
  UI-MVC/Controllers/AdminController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/Models/AssignRoleModel.cs
  UI-MVC/Services/RoleService.cs
  UI-MVC/Services/UserService.cs
  UI-MVC/Startup.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/AddTag.cshtml
  UI-MVC/Views/Moderation/CollectAllUsers.cshtml
  UI-MVC/Views/Moderation/ModerationTemplates/AssignRolePartial.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
  UI-MVC/appsettings.json
  UI-MVC/webpack.config.js
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/showmenu.entry.js
  UI-MVC/wwwroot/dist/showmenu.entry.js.map
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/js/showmenu.js
Labels: Dev branch, Master Worthy

#110 Fully refractored remove-idea
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
Labels: Dev branch, Not Ready For Master

#116 Feature/logged in/flag idea
  BL/IdeationQuestionManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Controllers/ThreadController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Dev branch, Learning Git

#117 Feature/logged in/remove idea
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/Thread/_CollectIdea.cshtml
Labels: Dev branch, Learning Git

#118 Fixes for users
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Services/RoleService.cs
  UI-MVC/TheSpanishDatabase.db
  UI-MVC/Views/Moderation/CollectAllUsers.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Dev branch, Master Worthy

#146 Patch/search checkboxoptions
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/Views/Moderation/ChangeIdeation.cshtml
  UI-MVC/Views/Platform/Search.cshtml
Labels: Master Worthy, Master branch
