Repository NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819, pull requests merged in 2019-04, with the labels that each got.

#18 Adding scripts
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  README.md
Labels: Not ready for Master

#23 Database implementation
  DAL/Contexts/COI_DbInitializer.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/DAL.csproj
  DAL/Data Transfer Objects/AnswersDTO.cs
  DAL/Data Transfer Objects/ChoicesDTO.cs
  DAL/Data Transfer Objects/DevicesDTO.cs
  DAL/Data Transfer Objects/IdeaFieldsDTO.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/Data Transfer Objects/IdeationQuestionsDTO.cs
  DAL/Data Transfer Objects/ModulesDTO.cs
  DAL/Data Transfer Objects/OptionsDTO.cs
  DAL/Data Transfer Objects/OrganisationEventsDTO.cs
  DAL/Data Transfer Objects/PhasesDTO.cs
  DAL/Data Transfer Objects/PlatformsDTO.cs
  DAL/Data Transfer Objects/ProjectImagesDTO.cs
  DAL/Data Transfer Objects/ProjectsDTO.cs
  DAL/Data Transfer Objects/QuestionnaireQuestionsDTO.cs
  DAL/Data Transfer Objects/UserActivitiesDTO.cs
  DAL/Data Transfer Objects/UserDetailsDTO.cs
  DAL/Data Transfer Objects/UsersDTO.cs
  DAL/Data Transfer Objects/VotesDTO.cs
Labels: Not Ready For Master

#26 Updates to User
  DAL/DAL.csproj
  UI-MVC/Areas/Identity/Data/UIMVCUser.cs
  UI-MVC/UIMVC.db
Labels: Not Ready For Master

#28 Epic dal giant reform
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DAL/repos/UserRepository.cs
Labels: Not Ready For Master

#41 UI landing
  DAL/repos/IRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/Index.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml.cs
  UI-MVC/Controllers/ErrorsController.cs
  UI-MVC/Controllers/HomeController.cs
  UI-MVC/Properties/launchSettings.json
  UI-MVC/ScaffoldingReadme.txt
  UI-MVC/Startup.cs
  UI-MVC/UIMVC.csproj
  UI-MVC/UIMVC.db
  UI-MVC/Views/Errors/HandleErrorCode.cshtml
  UI-MVC/Views/Home/Index.cshtml
  UI-MVC/Views/Home/PlatformTemplates/PlatformList.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/package-lock.json
  UI-MVC/package.json
  UI-MVC/webpack.config.js
  UI-MVC/wwwroot/css/site.css
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.css
  UI-MVC/wwwroot/dist/site.css.map
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/images/ErrorImage.jpg
  UI-MVC/wwwroot/images/Google.svg
  UI-MVC/wwwroot/js/site.js
Labels: Not Ready For Master

#42 Bl lineup issue#40
  BL/BL.csproj
  BL/IQuestionManager.cs
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  BL/PlatformManager.cs
  BL/ProjectManager.cs
  BL/QuestionnaireQuestionManager.cs
  BL/UserManager.cs
  BL/VoteManager.cs
  DAL/Data Transfer Objects/AnswersDTO.cs
  DAL/Data Transfer Objects/ChoicesDTO.cs
  DAL/Data Transfer Objects/IdeaFieldsDTO.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/Data Transfer Objects/IdeationQuestionsDTO.cs
  DAL/Data Transfer Objects/OptionsDTO.cs
  DAL/Data Transfer Objects/OrganisationEventsDTO.cs
  DAL/Data Transfer Objects/PhasesDTO.cs
  DAL/Data Transfer Objects/QuestionnaireQuestionsDTO.cs
  DAL/Data Transfer Objects/UserActivitiesDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DAL/repos/UserRepository.cs
  IP-TSI-CityOfIdeas.sln
  UI-MVC/package-lock.json
Labels: Master Worthy

#46 IP13-48 | Feature/web/moderator/summary of ideas
  BL/IdeationQuestionManager.cs
  DAL/Contexts/COI_DbInitializer.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/DAL.csproj
  DAL/Data Transfer Objects/AnswersDTO.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/Data Transfer Objects/UserActivitiesDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/UserRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Common/Media.cs
  IP-TSI-CityOfIdeas.sln
  Testing/IP1_TSI_DB.db
  Testing/Program.cs
  Testing/Testing.csproj
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/HomeController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Models/UserViewModel.cs
  UI-MVC/Startup.cs
  UI-MVC/UIMVC.csproj
  UI-MVC/UIMVC.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/appsettings.json
Labels: Master Worthy

#47 First Feature by Me | IP13-48
  BL/IdeationQuestionManager.cs
  BL/PlatformManager.cs
  DAL/Contexts/COI_DbInitializer.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/DAL.csproj
  DAL/Data Transfer Objects/AnswersDTO.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/Data Transfer Objects/UserActivitiesDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/UserRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Common/Media.cs
  IP-TSI-CityOfIdeas.sln
  Testing/IP1_TSI_DB.db
  Testing/Program.cs
  Testing/Testing.csproj
  UI-MVC/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
  UI-MVC/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  UI-MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Login.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml
  UI-MVC/Areas/Identity/Pages/Account/Register.cshtml.cs
  UI-MVC/Controllers/ErrorsController.cs
  UI-MVC/Controllers/HomeController.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Models/UserViewModel.cs
  UI-MVC/Notas.txt
  UI-MVC/Startup.cs
  UI-MVC/UIMVC.csproj
  UI-MVC/UIMVC.db
  UI-MVC/Views/Errors/ConfirmAccount.cshtml
  UI-MVC/Views/Errors/HandleErrorCode.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Shared/_Layout.cshtml
  UI-MVC/appsettings.json
  UI-MVC/package-lock.json
  UI-MVC/wwwroot/js/confirmemail.js
Labels: Master Worthy

#52 Feature/web/moderator/manage report
  BL/IdeationQuestionManager.cs
  BL/UserManager.cs
  DAL/Contexts/CityOfIdeasDbContext.cs
  DAL/Data Transfer Objects/IdeaFieldsDTO.cs
  DAL/Data Transfer Objects/IdeasDTO.cs
  DAL/Data Transfer Objects/IdeationQuestionsDTO.cs
  DAL/Data Transfer Objects/ReportsDTO.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DAL/repos/UserRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/UserInput/Field.cs
  Domain/UserInput/Idea.cs
  Domain/UserInput/IdeationQuestion.cs
  Domain/UserInput/Report.cs
  Domain/UserInput/ReportStatus.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/UIMVC.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/package-lock.json
  UI-MVC/package.json
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/bootstrap_js.entry.js
  UI-MVC/wwwroot/dist/bootstrap_js.entry.js.map
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/dist/validation.entry.js
  UI-MVC/wwwroot/dist/validation.entry.js.map
Labels: Master Worthy

#56 Code Conventions & Functionaliteiten
  BL/IdeationQuestionManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/ChangePlatform.cshtml
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#57 THE FIRST EVER DAL INQUISITION, NEVER EXPECTED
  BL/PlatformManager.cs
  BL/ProjectManager.cs
  BL/UserManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/IdeationVoteRepository.cs
  DAL/repos/PlatformRepository.cs
  DAL/repos/ProjectRepository.cs
  DAL/repos/QuestionnaireQuestionsRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DAL/repos/UserRepository.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#59 Feature/web/moderator/reported ideas
  DAL/repos/IdeationQuestionsRepository.cs
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/package-lock.json
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
  UI-MVC/wwwroot/js/collectallideas.js
  package-lock.json
Labels: Master Worthy

#62 Feature/web/user/view project
  BL/ModuleManager.cs
  BL/ProjectManager.cs
  DAL/Data Transfer Objects/IdeationsDTO.cs
  DAL/Data Transfer Objects/ModulesDTO.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Common/Media.cs
  Domain/Projects/Module.cs
  Domain/Projects/ModuleType.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Models/LikeViewModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/Views/Errors/ConfirmAccount.cshtml
  UI-MVC/Views/Home/HomeTemplates/PlatformList.cshtml
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Ideation.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Phase.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Project.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Questionnaire.cshtml
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Not Ready For Master

#63 Fix for layout module previews
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Ideation.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Questionnaire.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#65 Ideation is deftig
  BL/BL.csproj
  BL/IdeationQuestionManager.cs
  BL/ModuleManager.cs
  BL/PlatformManager.cs
  BL/ProjectManager.cs
  BL/QuestionnaireQuestionManager.cs
  BL/UserManager.cs
  BL/VoteManager.cs
  DAL/Data Transfer Objects/IdeationsDTO.cs
  DAL/Data Transfer Objects/ModulesDTO.cs
  DAL/repos/IdeationRepository.cs
  DAL/repos/QuestionnaireRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  DB-Scripts/IP1_TSI_SEED_SCRIPT.sql
  Domain/Common/Media.cs
  Domain/Projects/Module.cs
  Domain/Projects/ModuleType.cs
  UI-MVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/Controllers/PlatformController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Models/LikeViewModel.cs
  UI-MVC/Services/ProjectService.cs
  UI-MVC/Services/QuestionService.cs
  UI-MVC/Services/UserService.cs
  UI-MVC/Startup.cs
  UI-MVC/Views/Errors/ConfirmAccount.cshtml
  UI-MVC/Views/Home/HomeTemplates/PlatformList.cshtml
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CollectAllIdeas.cshtml
  UI-MVC/Views/Moderation/CollectIdea.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/CollectProject.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Ideation.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Phase.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Project.cshtml
  UI-MVC/Views/Platform/DisplayTemplates/Questionnaire.cshtml
  UI-MVC/Views/Platform/Index.cshtml
  UI-MVC/Views/Shared/_ReactionNumbersPartial.cshtml
  UI-MVC/Views/Shared/_TagsPartial.cshtml
  UI-MVC/wwwroot/css/site.scss
  UI-MVC/wwwroot/dist/site.entry.js
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy

#67 Feature/admin/ideation add cq
  BL/IdeationQuestionManager.cs
  DAL/repos/IdeationQuestionsRepository.cs
  DAL/repos/PlatformRepository.cs
  DB-Scripts/IP1_TSI_CREATE_SCRIPT.sql
  UI-MVC/Controllers/ModerationController.cs
  UI-MVC/IP1_TSI_DB.db
  UI-MVC/Models/CreateIdeationQuestionModel.cs
  UI-MVC/Views/Moderation/AddCentralQuestion.cshtml
  UI-MVC/Views/Moderation/AddPlatform.cshtml
  UI-MVC/Views/Moderation/CreatePlatform.cshtml
  UI-MVC/Views/Platform/CollectIdeation.cshtml
  UI-MVC/Views/Platform/EditPlatform.cshtml
  UI-MVC/wwwroot/dist/site.entry.js.map
Labels: Master Worthy
